### PR TITLE
Export Migrations fix.

### PR DESCRIPTION
**Pull request by yasaricli**
**Meteor 1.3** migrate this import error:

```
import { Migrations } from 'meteor/idmontie:migrations';

Migrations.add('memberIds', () => {
  console.log(Hello);
});
```
```
// ERROR
TypeError: Cannot call method 'add' of undefined
```

fixed; please merge pull request.

### CODE REVIEW

**Comment by yasaricli** [comment]
ping @idmontie

**Comment by idmontie** [comment]
Will up version on atmosphere when I get the chance

**Comment by yasaricli** [comment]
@idmontie no problem. before versions are supported.

**Comment by yasaricli** [comment]
@idmontie thanks.

**Comment by mquandalle** [comment]
@idmontie, I'm also running into this issue, could you release the fix to atmosphere?

**Comment by idmontie** [comment]
Published v1.0.2

**Pull request closed without merging**
